import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { JwtService } from '@nestjs/jwt';
import { UserEntity } from './entities/user.entity';
import { WalletEntity } from '../wallets/entities/wallet.entity';

@Injectable()
export class AuthService {
  constructor(
    @InjectRepository(UserEntity)
    private readonly userRepository: Repository<UserEntity>,
    @InjectRepository(WalletEntity)
    private readonly walletRepository: Repository<WalletEntity>,
    private readonly jwtService: JwtService,
  ) {}

  /**
   * Validate and create/update user from Google OAuth
   * This is called by the GoogleStrategy after successful Google authentication
   */
  async validateGoogleUser(googleUser: {
    googleId: string;
    email: string;
    name: string;
  }): Promise<UserEntity> {
    // Check if user already exists by Google ID
    let user = await this.userRepository.findOne({
      where: { googleId: googleUser.googleId },
      relations: ['wallet'],
    });

    if (user) {
      // User exists, update their info if changed
      if (user.email !== googleUser.email || user.name !== googleUser.name) {
        user.email = googleUser.email;
        user.name = googleUser.name;
        user = await this.userRepository.save(user);
      }
      return user;
    }

    // Check if user exists by email (edge case: same email, different Google account)
    user = await this.userRepository.findOne({
      where: { email: googleUser.email },
      relations: ['wallet'],
    });

    if (user) {
      // Update Google ID for existing user
      user.googleId = googleUser.googleId;
      return await this.userRepository.save(user);
    }

    // Create new user with wallet
    return await this.createUserWithWallet(googleUser);
  }

  /**
   * Create a new user and their associated wallet
   * Uses transaction to ensure both are created or neither
   */
  private async createUserWithWallet(googleUser: {
    googleId: string;
    email: string;
    name: string;
  }): Promise<UserEntity> {
    // Create user entity
    const user = this.userRepository.create({
      googleId: googleUser.googleId,
      email: googleUser.email,
      name: googleUser.name,
    });

    // Save user first
    const savedUser = await this.userRepository.save(user);

    // Create wallet for user
    const wallet = this.walletRepository.create({
      userId: savedUser.id,
      balance: 0,
      // walletNumber will be auto-generated by @BeforeInsert hook
    });

    await this.walletRepository.save(wallet);

    // Return user with wallet relation
    const userWithWallet = await this.userRepository.findOne({
      where: { id: savedUser.id },
      relations: ['wallet'],
    });

    if (!userWithWallet) {
      throw new Error('Failed to create user with wallet');
    }

    return userWithWallet;
  }

  /**
   * Generate JWT token for authenticated user
   */
  async generateJwtToken(user: UserEntity): Promise<string> {
    const payload = {
      sub: user.id,
      email: user.email,
      name: user.name,
    };

    return this.jwtService.sign(payload);
  }

  /**
   * Login user and return JWT token with user info
   */
  async login(user: UserEntity) {
    const token = await this.generateJwtToken(user);

    return {
      access_token: token,
      user: {
        id: user.id,
        email: user.email,
        name: user.name,
        wallet: user.wallet
          ? {
              id: user.wallet.id,
              walletNumber: user.wallet.walletNumber,
              balance: user.wallet.balance,
            }
          : null,
      },
    };
  }

  /**
   * Find user by ID (used by JWT strategy)
   */
  async findUserById(userId: string): Promise<UserEntity | null> {
    return await this.userRepository.findOne({
      where: { id: userId },
      relations: ['wallet'],
    });
  }

  /**
   * Find user by email
   */
  async findUserByEmail(email: string): Promise<UserEntity | null> {
    return await this.userRepository.findOne({
      where: { email },
      relations: ['wallet'],
    });
  }

  /**
   * Find user by Google ID
   */
  async findUserByGoogleId(googleId: string): Promise<UserEntity | null> {
    return await this.userRepository.findOne({
      where: { googleId },
      relations: ['wallet'],
    });
  }
}
